PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Students(FirstName VARCHAR(50) NOT NULL, LastName VARCHAR(50) NOT NULL, StudentID INT PRIMARY KEY NOT NULL);
CREATE TABLE Quizzes(QuizID INT PRIMARY KEY NOT NULL, SUBJECT VARCHAR(20) NOT NULL, NUMBEROFQUESTIONS INT NOT NULL, QUIZDATE DATE);
CREATE TABLE Results(StudentID INT NOT NULL, QuizID INT NOT NULL, Score INT NOT NULL);
COMMIT;
